export const ERROR_CODES = {
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
  },
  TRANSFER: {
    INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
    INVALID_AMOUNT: 'INVALID_TRANSFER_AMOUNT',
  },
} as const;
